name = "cf_ai_newsletter"
main = "src/index.ts"
compatibility_date = "2024-03-20" # Or your project's date

# To set the NewsAPI key as a secret in production, run:
# npx wrangler secret put NEWS_API_KEY
# Then enter your NewsAPI key: 65833a57006a47fbb61a092994a1df3c

[[d1_databases]]
binding = "DB" # This is how you'll access it in your code: env.DB
database_name = "newsletter-db"
database_id = "c22e14b1-4a1a-4819-a046-658169a6e35e"

[ai]
binding = "AI" # This is how you'll access it in your code: env.AI

[triggers]
crons = ["20 20 * * *"] #3:20 PM CDT daily (8:20 PM UTC)
