name = "cf_ai_newsletter"
main = "src/index.ts"
compatibility_date = "2024-03-20" # Or your project's date

# This new line tells wrangler where your static HTML/CSS/JS files are
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB" # This is how you'll access it in your code: env.DB
database_name = "newsletter-db"
database_id = "c22e14b1-4a1a-4819-a046-658169a6e35e"

[ai]
binding = "AI"

[triggers]
crons = ["0 13 * * *"] # 1:00 PM UTC daily. You can adjust this schedule.
