name = "cf_ai_newsletter"
main = "src/index.ts"
compatibility_date = "2024-03-20"

# To set the NewsAPI key as a secret in production, run:
# npx wrangler secret put NEWS_API_KEY

[[d1_databases]]
binding = "DB" # This is how you'll access it in your code: env.DB
database_name = "newsletter-db"
database_id = "c22e14b1-4a1a-4819-a046-658169a6e35e"

[ai]
binding = "AI" # This is how you'll access it in your code: env.AI

[triggers]
crons = ["0 13 * * *"] # 1:00 PM UTC daily (8:00 AM CDT)